version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=meetify_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    app:
      build: .
      ports:
        - "8000:8000"
      volumes:
        - ./app:/code/app
      env_file:
        - ./env
      depends_on:
        - db

  volumes:
    db_data: